
language: objective-c

before_install:
    - gem install cocoapods --pre --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - pod lib lint RBVolumeButtons@PTEz.podspec
    - xctool -project 'VolumeSnap.xcodeproj' -scheme 'VolumeSnap' -configuration Release -sdk iphonesimulator -arch i386 build
